trigger:
  branches:
    include:
      - main

pool:
  name: macOS-pool  # Name of your self-hosted agent pool

variables:
  MAVEN_OPTS: "-Xmx1024m"
  JAVA_HOME: /opt/homebrew/Cellar/openjdk/23.0.2/libexec/openjdk.jdk/Contents/Home

steps:

# Print Java version
- script: java -version
  displayName: 'Check Java version'

# Print Maven version
- script: mvn -version
  displayName: 'Check Maven version'

# Restore dependencies (optional, if using a cache strategy)
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'